// Reviewed dispositions for every agency constellation source id outside the
// publisher crosswalk. These are exact aliases or explicit non-merges, never
// fuzzy name guesses. The browser-facing resolver keeps only the compact route
// data it needs; this build-time census carries the report evidence.
export const AGENCY_ROUTE_CLASSIFICATIONS = Object.freeze([
  { source_id: "board-meetings", source_name: "Board Meetings", classification: "unresolved", canonical_id: "board-meetings", canonical_name: "Board Meetings", basis: "generic publisher label does not identify one agency" },
  { source_id: "board-of-corrections", source_name: "Board Of Corrections", classification: "alias_to_canonical", canonical_id: "board-of-correction", canonical_name: "Board of Correction", basis: "punctuation-insensitive singular/plural publisher alias" },
  { source_id: "dcasdivision-of-municipal-supply-service", source_name: "DCASDIVISION OF MUNICIPAL SUPPLY SERVICE", classification: "alias_to_canonical", canonical_id: "citywide-administrative-services", canonical_name: "Citywide Administrative Services", basis: "named DCAS division" },
  { source_id: "department-of-social-services", source_name: "Department of Social Services", classification: "legitimate_non_crosswalk_entity", canonical_id: "department-of-social-services", canonical_name: "Department of Social Services", basis: "publisher body retained separately from its HRA and Homeless Services components" },
  { source_id: "district-attorney-special-narcotics", source_name: "District Attorney - Special Narcotics", classification: "alias_to_canonical", canonical_id: "office-of-special-narcotics-prosecutor", canonical_name: "Office of Special Narcotics Prosecutor", basis: "reviewed publisher rename" },
  { source_id: "hra-department-of-social-services", source_name: "HRA/Department Of Social Services", classification: "alias_to_canonical", canonical_id: "human-resources-administration", canonical_name: "Human Resources Administration", basis: "publisher crosswalk variant" },
  { source_id: "mayoralty", source_name: "Mayoralty", classification: "alias_to_canonical", canonical_id: "office-of-the-mayor", canonical_name: "Office of the Mayor", basis: "publisher budget-code identity" },
  { source_id: "n-y-c-housing-authority", source_name: "N.Y.C. Housing Authority", classification: "alias_to_canonical", canonical_id: "housing-authority", canonical_name: "Housing Authority", basis: "punctuation-only publisher alias" },
  { source_id: "n-y-c-transit-authority", source_name: "N.Y.C. Transit Authority", classification: "legitimate_non_crosswalk_entity", canonical_id: "n-y-c-transit-authority", canonical_name: "N.Y.C. Transit Authority", basis: "distinct MTA operating authority; no parent merge" },
  { source_id: "new-york-city-fire-pension-fund", source_name: "New York City Fire Pension Fund", classification: "legitimate_non_crosswalk_entity", canonical_id: "new-york-city-fire-pension-fund", canonical_name: "New York City Fire Pension Fund", basis: "distinct pension fund absent from the publisher identity set" },
  { source_id: "new-york-city-police-department", source_name: "New York City Police Department", classification: "alias_to_canonical", canonical_id: "police-department", canonical_name: "Police Department", basis: "publisher crosswalk canonical name" },
  { source_id: "nyc-employees-retirement-system", source_name: "NYC Employees' Retirement System", classification: "alias_to_canonical", canonical_id: "employees-retirement-system", canonical_name: "Employees' Retirement System", basis: "punctuation and city-prefix publisher alias" },
  { source_id: "nyc-health-and-hospitals-corporation", source_name: "NYC Health And Hospitals Corporation", classification: "alias_to_canonical", canonical_id: "nyc-health-hospitals", canonical_name: "NYC Health + Hospitals", basis: "reviewed publisher former-name alias" },
  { source_id: "nyc-police-pension-fund", source_name: "NYC Police Pension Fund", classification: "alias_to_canonical", canonical_id: "new-york-city-police-pension-fund", canonical_name: "New York City Police Pension Fund", basis: "publisher crosswalk canonical name" },
  { source_id: "office-of-administrative-trials-and-hearings", source_name: "Office Of Administrative Trials And Hearings", classification: "alias_to_canonical", canonical_id: "administrative-trials-and-hearings", canonical_name: "Administrative Trials and Hearings", basis: "department-prefix publisher alias" },
  { source_id: "office-of-contract-services", source_name: "Office Of Contract Services", classification: "alias_to_canonical", canonical_id: "mayors-office-of-contract-services", canonical_name: "Mayor's Office of Contract Services", basis: "publisher crosswalk canonical office" },
  { source_id: "office-of-criminal-justice-002", source_name: "Office Of Criminal Justice (002)", classification: "alias_to_canonical", canonical_id: "mayors-office-of-criminal-justice", canonical_name: "Mayor's Office of Criminal Justice", basis: "publisher budget-code identity" },
  { source_id: "office-of-payroll-administration", source_name: "Office Of Payroll Administration", classification: "alias_to_canonical", canonical_id: "payroll-administration", canonical_name: "Payroll Administration", basis: "department-prefix publisher alias" },
  { source_id: "office-of-the-chief-medical-examiner", source_name: "Office Of The Chief Medical Examiner", classification: "alias_to_canonical", canonical_id: "chief-medical-examiner", canonical_name: "Office of the Chief Medical Examiner", basis: "department-prefix publisher alias" },
  { source_id: "triborough-bridge-and-tunnel-authority", source_name: "Triborough Bridge And Tunnel Authority", classification: "legitimate_non_crosswalk_entity", canonical_id: "triborough-bridge-and-tunnel-authority", canonical_name: "Triborough Bridge and Tunnel Authority", basis: "distinct MTA operating authority; no parent merge" },
].map((row) => Object.freeze(row)));
