// Data-frontiers register: per-entry records + generated markdown projection.
//
// Source of truth for each ranked row is a JSON file under
// docs/data-frontiers/<edition>/entries/. Concurrent cranks update only the
// entry they own; the human-readable table in docs/data-frontiers-YYYY-MM.md
// is regenerated by tools/build_data_frontiers.mjs and must not be hand-edited
// for disposition updates.

import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
  readdirSync,
} from "node:fs";
import { join, dirname } from "node:path";

export const FRONTIER_ENTRY_SCHEMA = "cityscroll.data_frontier_entry.v0";
export const FRONTIER_META_SCHEMA = "cityscroll.data_frontiers_meta.v0";

export const TABLE_COLUMNS = [
  "rank",
  "gap_inventory_row",
  "source_and_access",
  "join_feasibility",
  "reader_value",
  "effort",
  "disposition",
];

/**
 * Stable entry filename: zero-padded rank + id slug.
 * @param {{ rank: number, id: string }} entry
 */
export function frontierEntryFilename(entry) {
  const rank = String(entry.rank).padStart(2, "0");
  const slug = String(entry.id || "row")
    .replace(/[^a-zA-Z0-9._-]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return `${rank}-${slug}.json`;
}

/**
 * Extract a stable gap id from the "Gap inventory row" cell.
 * Prefers backtick-wrapped tokens like `procurement-planning-budget`.
 * @param {string} gapCell
 */
export function gapIdFromCell(gapCell) {
  const text = String(gapCell || "");
  const tick = text.match(/`([a-z0-9][a-z0-9_-]+)`/i);
  if (tick) return tick[1];
  const rc = text.match(/\*\*RC-(\d+)\*\*/i);
  if (rc) return `rc-${rc[1]}`;
  return text
    .replace(/\*\*/g, "")
    .replace(/\(new\)/gi, "")
    .replace(/—.*$/, "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80) || "row";
}

/**
 * Parse a GitHub-flavored markdown table body into row objects.
 * Expects a header line, a separator line, then data rows.
 * @param {string} tableMarkdown
 */
export function parseMarkdownTable(tableMarkdown) {
  const lines = String(tableMarkdown || "")
    .split("\n")
    .map((l) => l.trimEnd())
    .filter((l) => l.trim().startsWith("|"));
  if (lines.length < 3) return [];
  const splitRow = (line) => {
    const raw = line.trim().replace(/^\|/, "").replace(/\|$/, "");
    // Cells may contain escaped pipes rarely; split on unescaped |
    const cells = [];
    let cur = "";
    for (let i = 0; i < raw.length; i++) {
      const ch = raw[i];
      if (ch === "\\" && raw[i + 1] === "|") {
        cur += "|";
        i += 1;
        continue;
      }
      if (ch === "|") {
        cells.push(cur.trim());
        cur = "";
        continue;
      }
      cur += ch;
    }
    cells.push(cur.trim());
    return cells;
  };
  const header = splitRow(lines[0]).map((h) => h.toLowerCase());
  // skip separator lines[1]
  const rows = [];
  for (const line of lines.slice(2)) {
    if (/^\|\s*:?-{3,}/.test(line)) continue;
    const cells = splitRow(line);
    if (cells.length < 2) continue;
    const obj = {};
    for (let i = 0; i < header.length; i++) {
      obj[header[i] || `col_${i}`] = cells[i] ?? "";
    }
    rows.push(obj);
  }
  return rows;
}

/**
 * Convert a parsed table row (header keys as in the markdown) into a frontier entry.
 * @param {object} row
 * @param {number} [index]
 */
export function tableRowToEntry(row, index = 0) {
  const gap = row["gap inventory row"] || row.gap_inventory_row || "";
  const rank = Number(row.rank) || index + 1;
  const id = gapIdFromCell(gap);
  const rcMatch = String(gap).match(/\*\*RC-(\d+)\*\*/i);
  return {
    schema: FRONTIER_ENTRY_SCHEMA,
    id,
    rank,
    ...(rcMatch ? { rc: `RC-${rcMatch[1]}` } : {}),
    gap_inventory_row: gap,
    source_and_access: row["source and access mechanics"] || row.source_and_access || "",
    join_feasibility: row["join feasibility"] || row.join_feasibility || "",
    reader_value: row["reader value"] || row.reader_value || "",
    effort: row.effort || "",
    disposition: row.disposition || "",
  };
}

/**
 * Render one entry as a markdown table row (leading/trailing pipes).
 * @param {object} entry
 */
export function entryToTableRow(entry) {
  const cells = [
    entry.rank,
    entry.gap_inventory_row,
    entry.source_and_access,
    entry.join_feasibility,
    entry.reader_value,
    entry.effort,
    entry.disposition,
  ].map((c) => String(c ?? "").replace(/\|/g, "\\|").replace(/\n/g, " "));
  return `| ${cells.join(" | ")} |`;
}

/**
 * Render the full ranked frontier table from sorted entries.
 * @param {object[]} entries
 */
export function renderRankedTable(entries) {
  const header =
    "| Rank | Gap inventory row | Source and access mechanics | Join feasibility | Reader value | Effort | Disposition |";
  const sep = "|---:|---|---|---|---|---|---|";
  const sorted = [...entries].sort((a, b) => a.rank - b.rank || a.id.localeCompare(b.id));
  const body = sorted.map(entryToTableRow);
  return [header, sep, ...body].join("\n");
}

/**
 * Load all entry JSON files from a directory (sorted by rank then id).
 * @param {string} entriesDir
 */
export function loadFrontierEntries(entriesDir) {
  if (!existsSync(entriesDir)) return [];
  const entries = [];
  for (const name of readdirSync(entriesDir).sort()) {
    if (!name.endsWith(".json")) continue;
    const raw = JSON.parse(readFileSync(join(entriesDir, name), "utf8"));
    entries.push(raw);
  }
  return entries.sort((a, b) => a.rank - b.rank || String(a.id).localeCompare(String(b.id)));
}

/**
 * Write entry files. Only overwrites files for the provided entries.
 * @param {string} entriesDir
 * @param {object[]} entries
 * @param {{ removeMissing?: boolean }} [opts]
 */
export function writeFrontierEntries(entriesDir, entries, opts = {}) {
  mkdirSync(entriesDir, { recursive: true });
  const written = [];
  const keep = new Set();
  for (const entry of entries) {
    const name = frontierEntryFilename(entry);
    keep.add(name);
    const path = join(entriesDir, name);
    const doc = {
      schema: FRONTIER_ENTRY_SCHEMA,
      id: entry.id,
      rank: entry.rank,
      ...(entry.rc ? { rc: entry.rc } : {}),
      gap_inventory_row: entry.gap_inventory_row,
      source_and_access: entry.source_and_access,
      join_feasibility: entry.join_feasibility,
      reader_value: entry.reader_value,
      effort: entry.effort,
      disposition: entry.disposition,
    };
    writeFileSync(path, `${JSON.stringify(doc, null, 2)}\n`);
    written.push(name);
  }
  if (opts.removeMissing) {
    for (const name of readdirSync(entriesDir)) {
      if (!name.endsWith(".json")) continue;
      if (!keep.has(name)) {
        // leave delete to caller with fs.unlink if needed — keep pure-ish
      }
    }
  }
  return written;
}

/**
 * Split a full frontiers markdown document into: before table, table body, after table.
 * @param {string} markdown
 */
export function splitFrontiersMarkdown(markdown) {
  const text = String(markdown || "");
  const tableStart = text.indexOf("| Rank | Gap inventory row |");
  if (tableStart < 0) {
    throw new Error("ranked frontier table header not found");
  }
  // Walk from tableStart to the first blank line after the table rows
  const afterHeader = text.slice(tableStart);
  const lines = afterHeader.split("\n");
  const tableLines = [];
  for (const line of lines) {
    if (tableLines.length > 0 && line.trim() === "") break;
    if (tableLines.length > 0 && !line.trim().startsWith("|")) break;
    tableLines.push(line);
  }
  const tableMarkdown = tableLines.join("\n");
  const before = text.slice(0, tableStart);
  const after = text.slice(tableStart + tableMarkdown.length).replace(/^\n/, "");
  return { before, tableMarkdown, after };
}

/**
 * Rebuild full markdown from before/after fragments + entries.
 * @param {{ before: string, after: string }} fragments
 * @param {object[]} entries
 */
export function renderFrontiersMarkdown(fragments, entries) {
  const table = renderRankedTable(entries);
  const before = fragments.before.endsWith("\n") ? fragments.before : `${fragments.before}\n`;
  const after = fragments.after.startsWith("\n") ? fragments.after : `\n${fragments.after}`;
  return `${before}${table}\n${after}`;
}

/**
 * Paths for an edition (e.g. 2026-08).
 * @param {string} root — repo root
 * @param {string} edition
 */
export function frontierEditionPaths(root, edition = "2026-08") {
  const base = join(root, "docs/data-frontiers", edition);
  return {
    base,
    entriesDir: join(base, "entries"),
    metaPath: join(base, "meta.json"),
    fragmentsDir: join(base, "fragments"),
    beforePath: join(base, "fragments", "before.md"),
    afterPath: join(base, "fragments", "after.md"),
    projectionPath: join(root, `docs/data-frontiers-${edition}.md`),
  };
}

/**
 * Migrate a committed projection markdown into per-entry records + fragments.
 * @param {string} root
 * @param {string} edition
 */
export function migrateFrontiersFromMarkdown(root, edition = "2026-08") {
  const paths = frontierEditionPaths(root, edition);
  const md = readFileSync(paths.projectionPath, "utf8");
  const { before, tableMarkdown, after } = splitFrontiersMarkdown(md);
  const rows = parseMarkdownTable(tableMarkdown);
  const entries = rows.map((row, i) => tableRowToEntry(row, i));
  mkdirSync(paths.fragmentsDir, { recursive: true });
  writeFileSync(paths.beforePath, before);
  writeFileSync(paths.afterPath, after.startsWith("\n") ? after.slice(1) : after);
  writeFrontierEntries(paths.entriesDir, entries);
  const meta = {
    schema: FRONTIER_META_SCHEMA,
    edition,
    entry_count: entries.length,
    projection: `docs/data-frontiers-${edition}.md`,
    note:
      "Per-entry records under entries/ are the source of truth for the ranked table. Rebuild the projection with node tools/build_data_frontiers.mjs.",
  };
  writeFileSync(paths.metaPath, `${JSON.stringify(meta, null, 2)}\n`);
  return { paths, entries, meta };
}

/**
 * Build the projection markdown from fragments + entries.
 * @param {string} root
 * @param {string} edition
 * @param {{ check?: boolean }} [opts]
 */
export function buildFrontiersProjection(root, edition = "2026-08", opts = {}) {
  const paths = frontierEditionPaths(root, edition);
  if (!existsSync(paths.entriesDir)) {
    throw new Error(`missing frontier entries dir: ${paths.entriesDir}`);
  }
  const before = existsSync(paths.beforePath)
    ? readFileSync(paths.beforePath, "utf8")
    : "";
  const after = existsSync(paths.afterPath)
    ? readFileSync(paths.afterPath, "utf8")
    : "";
  const entries = loadFrontierEntries(paths.entriesDir);
  const text = renderFrontiersMarkdown({ before, after }, entries);
  if (opts.check) {
    if (!existsSync(paths.projectionPath)) {
      throw new Error(`missing projection for --check: ${paths.projectionPath}`);
    }
    const existing = readFileSync(paths.projectionPath, "utf8");
    if (existing !== text) {
      const err = new Error("data-frontiers projection drift vs entries");
      err.expected = text;
      err.actual = existing;
      throw err;
    }
    return { paths, entries, text, checked: true };
  }
  mkdirSync(dirname(paths.projectionPath), { recursive: true });
  writeFileSync(paths.projectionPath, text);
  return { paths, entries, text, checked: false };
}
