// Cross-domain object-link layer (entity_resolution package surface).

export {
  CROSS_DOMAIN_OBJECT_LINK_VERSION,
  CROSS_DOMAIN_METHOD,
  CROSS_DOMAIN_METHOD_VERSION,
  CROSS_DOMAIN_DOMAINS,
  CROSS_DOMAIN_LINK_TYPES,
  AGENCY_METHOD,
  AGENCY_METHOD_VERSION,
  PIN_METHOD,
  PIN_METHOD_VERSION,
  CONTRACT_METHOD,
  CONTRACT_METHOD_VERSION,
  PAYMENT_METHOD,
  PAYMENT_METHOD_VERSION,
  resolveAgencySubject,
  resolveVendorSubject,
  resolveRootQuery,
  makeProvenance,
  makeObjectLink,
  observationFromMoneyRow,
  observationFromPaymentRow,
  observationFromLandRow,
  observationFromZapBblRow,
  observationFromRulesRow,
  observationFromMeetingsRow,
  observationFromPeopleRow,
  normalizeBbl,
  resolveParcelSubject,
  mergeBblsOntoLandObservations,
  rootsForObservation,
  linkObservation,
  joinKeyLinksForObservation,
  indexObservationsByRoot,
  dedupeObjectLinks,
  buildEntityIntelligence,
  buildEntityIntelligenceFromBucket,
  buildIntelligenceCorpus,
  lookupEntityIntelligence,
} from "./object_links.mjs";
