// Cross-domain object-link layer (entity_resolution package surface).

export {
  CROSS_DOMAIN_OBJECT_LINK_VERSION,
  CROSS_DOMAIN_METHOD,
  CROSS_DOMAIN_METHOD_VERSION,
  CROSS_DOMAIN_DOMAINS,
  CROSS_DOMAIN_LINK_TYPES,
  AGENCY_METHOD,
  AGENCY_METHOD_VERSION,
  PIN_METHOD,
  PIN_METHOD_VERSION,
  CONTRACT_METHOD,
  CONTRACT_METHOD_VERSION,
  PAYMENT_METHOD,
  PAYMENT_METHOD_VERSION,
  MEETING_LAND_ULURP_METHOD,
  MEETING_LAND_ULURP_METHOD_VERSION,
  MEETING_LAND_ZAP_METHOD,
  MEETING_LAND_ZAP_METHOD_VERSION,
  resolveAgencySubject,
  resolveVendorSubject,
  resolveRootQuery,
  makeProvenance,
  makeObjectLink,
  makeExactKeyObjectLink,
  EXACT_KEY_EDGE_TIER,
  EXACT_KEY_EDGE_TIER_VERSION,
  observationFromMoneyRow,
  observationFromPassportContractRow,
  observationFromCheckbookContractRow,
  observationFromPaymentRow,
  procurementContractLinksForObservations,
  observationFromLandRow,
  observationFromZapBblRow,
  observationFromRulesRow,
  observationFromMeetingsRow,
  observationFromPeopleRow,
  observationFromFranchise,
  observationFromFranchiseRow,
  flattenRulesMaterializationRecord,
  flattenMeetingsMaterializationRecord,
  observationsFromRulesMaterialization,
  observationsFromMeetingsMaterialization,
  observationsFromPeopleMaterialization,
  observationsFromFranchiseMaterialization,
  hearingBodyBlob,
  extractZapProjectIds,
  extractMeetingLandRefs,
  buildLandProjectJoinIndex,
  resolveMeetingLandProjects,
  stampMeetingLandProjects,
  stampMeetingLandLinksOnCorpus,
  joinMeetingsToLandProjects,
  makeMeetingLandProjectLink,
  meetingLandLinksForObservation,
  normalizeBbl,
  resolveParcelSubject,
  mergeBblsOntoLandObservations,
  rootsForObservation,
  linkObservation,
  joinKeyLinksForObservation,
  indexObservationsByRoot,
  dedupeObjectLinks,
  pickDiversePeopleObjects,
  buildEntityIntelligence,
  buildEntityIntelligenceFromBucket,
  buildIntelligenceCorpus,
  lookupEntityIntelligence,
} from "./object_links.mjs";

export {
  PROCUREMENT_CROSSWALK_VERSION,
  PROCUREMENT_CROSSWALK_METHOD,
  buildPassportCheckbookCrosswalk,
} from "./procurement_crosswalk.mjs";

// Property-domain helpers (normalizeBbl / observationFromZapBblRow live on object_links
// to avoid duplicate package exports; property_links keeps local copies for its joins).
export {
  PROPERTY_CROSS_DOMAIN_VERSION,
  BBL_JOIN_METHOD,
  observationFromPropertyRow,
  coercePropertyObservation,
  extractDispositionOwner,
  stripNoticeHtml,
  bblSubjectRef,
  bblsFromPropertyRow,
  linkPropertyObservation,
  joinPropertyToZapByBbl,
  joinPropertyOwnerToContracts,
  joinPropertyToLl48ByBbl,
  buildParcelIntelligence,
  buildPropertyCrossDomainDoc,
} from "./property_links.mjs";

export {
  CROSS_SPINE_EDGE_POLICY_SCHEMA,
  CROSS_SPINE_EDGE_POLICY_VERSION,
  CROSS_SPINE_MIN_HELD_OUT_PRECISION,
  CROSS_SPINE_MIN_HELD_OUT_SUPPORT,
  CROSS_SPINE_EDGE_TIERS,
  CROSS_SPINE_RELATION_POLICIES,
  DEFAULT_CROSS_SPINE_EDGE_POLICY,
  CROSS_SPINE_EDGE_POLICY_V1,
  canonicalCrossSpineRelation,
  crossSpineFeaturePasses,
  crossSpineRowFeatures,
  crossSpineEvidenceDecision,
  routeCrossSpineEdge,
  routeCrossSpineEdges,
  policyFromCrossSpineEval,
  checkCrossSpineEdgePolicy,
  promoteCrossSpineEdgePolicy,
  isCrossSpineCandidate,
} from "./edge_policy.mjs";
