/**
 * SEQRA/CEQR source registry: every source this workstream is authorized to
 * inventory, with the tier priority from the commission and the fields the
 * source-receipt contract requires. Runtime fields (`observed_latency`,
 * `last_success_at`, `last_row_count`, `last_content_hash`) start `null` and
 * are overlaid by a `--refresh` run; they never carry a fabricated value.
 *
 * `access_type` distinguishes what this card measures from what it only
 * inventories:
 *   - "soda_api": Tier 1 structured source profiled live over Socrata SODA.
 *   - "existing_internal_corpus": already materialized inside CityScroll;
 *     the SEQRA/CEQR-specific subset is not yet query-scoped.
 *   - "discovery_probe": a single bounded, polite HTTP request records
 *     reachability only -- never parsed into a population count.
 *   - "discovery_only": registered from the commission text with no live
 *     request attempted in SEQRA-01; a later card owns the adapter.
 */

export const SEQRA_SOURCE_REGISTRY_SCHEMA = "cityscroll.seqra_source_registry.v1";

function runtimeFields() {
  return {
    observed_latency: null,
    parser_version: "seqra_source_inventory.v1",
    last_success_at: null,
    last_row_count: null,
    last_content_hash: null,
  };
}

export const SEQRA_SOURCE_REGISTRY = Object.freeze([
  // ---- Tier 1: structured sources, profiled live over Socrata SODA ----
  {
    source_id: "ceqr_projects",
    source_name: "CEQR Projects",
    publisher: "NYC Mayor's Office of Environmental Coordination / NYC Open Data",
    jurisdiction_level: "NYC",
    environmental_regime: "CEQR",
    tier: 1,
    access_type: "soda_api",
    base_url: "https://data.cityofnewyork.us",
    dataset_identifier: "gezn-7mgk",
    coverage_start: "unknown",
    coverage_end: "current",
    update_frequency: "unknown",
    known_gaps: [
      "No explicit review-status or milestone-date field on the project row itself; use CEQR Project Milestones for event dates.",
      "No explicit source_jurisdiction/environmental_regime column; jurisdiction and regime are asserted by this registry from the publisher, not read from the row.",
    ],
    ...runtimeFields(),
  },
  {
    source_id: "ceqr_project_milestones",
    source_name: "CEQR Project Milestones",
    publisher: "NYC Mayor's Office of Environmental Coordination / NYC Open Data",
    jurisdiction_level: "NYC",
    environmental_regime: "CEQR",
    tier: 1,
    access_type: "soda_api",
    base_url: "https://data.cityofnewyork.us",
    dataset_identifier: "8fj8-3sgg",
    coverage_start: "unknown",
    coverage_end: "current",
    update_frequency: "unknown",
    known_gaps: [
      "No lead-agency field on the milestone row; joining to CEQR Projects for agency is out of scope for this inventory (see warehouse/lib/ceqr_project_milestone_reconciliation.mjs for the existing exact-key join).",
      "milestone_name is free text, not a controlled event-type vocabulary; event-type counts group on the raw published string.",
    ],
    ...runtimeFields(),
  },
  {
    source_id: "zap_projects",
    source_name: "ZAP Projects",
    publisher: "NYC Department of City Planning / NYC Open Data",
    jurisdiction_level: "NYC",
    environmental_regime: "CEQR",
    tier: 1,
    access_type: "soda_api",
    base_url: "https://data.cityofnewyork.us",
    dataset_identifier: "hgx4-8ukb",
    coverage_start: "unknown",
    coverage_end: "current",
    update_frequency: "unknown",
    known_gaps: [
      "project_status/public_status are land-use/ULURP statuses, not a dedicated environmental-review status; environmental review state comes from current_envmilestone.",
      "ceqr_number is not populated for every action row; see warehouse/lib/zap_environmental_projection.mjs presence typing for the measured gap.",
    ],
    ...runtimeFields(),
  },
  {
    source_id: "zap_bbl",
    source_name: "ZAP BBL",
    publisher: "NYC Department of City Planning / NYC Open Data",
    jurisdiction_level: "NYC",
    environmental_regime: "CEQR",
    tier: 1,
    access_type: "soda_api",
    base_url: "https://data.cityofnewyork.us",
    dataset_identifier: "2iga-a6mk",
    coverage_start: "unknown",
    coverage_end: "current",
    update_frequency: "unknown",
    known_gaps: [
      "Parcel join-key table only; carries no year, agency, event-type, or review-status field, so those breakdowns are not_applicable for this source.",
    ],
    ...runtimeFields(),
  },
  {
    source_id: "nys_dec_dart",
    source_name: "NYS DEC DART (Department Application Review and Tracking)",
    publisher: "New York State Department of Environmental Conservation / data.ny.gov",
    jurisdiction_level: "NYS",
    environmental_regime: "SEQRA",
    tier: 1,
    access_type: "soda_api",
    base_url: "https://data.ny.gov",
    dataset_identifier: "mbk7-f2r2",
    coverage_start: "1988",
    coverage_end: "current",
    update_frequency: "unknown",
    known_gaps: [
      "seqr_class/seqr_determination cover state permit-linked SEQR review only; DART is a permit tracker, not the statewide SEQRA population of record.",
      "Measured directly: application_id repeats with fully identical row content in a large share of rows (a publisher data-quality characteristic, not a CityScroll dedupe artifact); see the duplicates.value in this source's profile for the exact measured rate.",
    ],
    ...runtimeFields(),
  },
  {
    source_id: "nyc_elobbyist",
    source_name: "NYC eLobbyist",
    publisher: "NYC Office of the City Clerk / NYC Open Data",
    jurisdiction_level: "NYC",
    environmental_regime: "CEQR",
    tier: 1,
    access_type: "soda_api",
    base_url: "https://data.cityofnewyork.us",
    dataset_identifier: "fmf3-knd8",
    coverage_start: "unknown",
    coverage_end: "current",
    update_frequency: "unknown",
    known_gaps: [
      "Dated institutional-activity context, not an environmental-review population; no CEQR/SEQRA key on the row. Reported for feasibility only; not a review-population denominator.",
    ],
    ...runtimeFields(),
  },
  {
    source_id: "nyc_city_record_corpus",
    source_name: "NYC City Record Online (existing CityScroll corpus/search source dataset)",
    publisher: "NYC Department of Citywide Administrative Services / NYC Open Data",
    jurisdiction_level: "NYC",
    environmental_regime: "CEQR",
    tier: 1,
    access_type: "soda_api",
    base_url: "https://data.cityofnewyork.us",
    dataset_identifier: "dg92-zbpx",
    coverage_start: "unknown",
    coverage_end: "current",
    update_frequency: "unknown",
    known_gaps: [
      "This inventory measures the whole City Record Online corpus (all notice types). It is not source-filtered for SEQRA/CEQR hearings, notices, or scoping events; a scoped environmental-review notice-type query has not been designed (deferred to SEQRA-07). The counts below are a whole-corpus feasibility measurement, not an environmental-review population.",
      "CityScroll already retains a derived City Record PIN-chain lookup (warehouse/lib/city_record_pin_chain_lookup.mjs) for a different purpose; this inventory queries the publisher dataset directly rather than that derived artifact so every count traces to its own fetch receipt.",
    ],
    ...runtimeFields(),
  },
  {
    source_id: "nyc_council_legislative_records",
    source_name: "NYC Council legislative records",
    publisher: "New York City Council / Legistar",
    jurisdiction_level: "NYC",
    environmental_regime: "CEQR",
    tier: 1,
    access_type: "discovery_probe",
    base_url: "https://webapi.legistar.com/v1/nyc",
    dataset_identifier: "legistar_nyc",
    coverage_start: "unknown",
    coverage_end: "current",
    update_frequency: "unknown",
    known_gaps: [
      "Legistar exposes a documented API, but a land-use/environmental-review-scoped query (matter type, committee) has not been designed in SEQRA-01; this card records interface reachability only, not a row count.",
    ],
    ...runtimeFields(),
  },
  {
    source_id: "nys_coelig_lobbying",
    source_name: "NYS COELIG lobbying records",
    publisher: "New York State Commission on Ethics and Lobbying in Government",
    jurisdiction_level: "NYS",
    environmental_regime: "SEQRA",
    tier: 1,
    access_type: "discovery_only",
    base_url: "https://ethics.ny.gov/lobbying-application",
    dataset_identifier: "unknown",
    coverage_start: "unknown",
    coverage_end: "unknown",
    update_frequency: "unknown",
    known_gaps: [
      "No documented bulk-download or API interface identified in this commission; state downloads/search page requires per-record navigation. Discovery deferred to a dedicated adapter card (institutional-signal work, SEQRA-07).",
    ],
    ...runtimeFields(),
  },

  // ---- Tier 2: review documents and notices (discovery only) ----
  {
    source_id: "ceqr_access",
    source_name: "CEQR Access",
    publisher: "NYC Mayor's Office of Environmental Coordination",
    jurisdiction_level: "NYC",
    environmental_regime: "CEQR",
    tier: 2,
    access_type: "discovery_probe",
    base_url: "https://a002-ceqraccess.nyc.gov",
    dataset_identifier: "unknown",
    coverage_start: "unknown",
    coverage_end: "current",
    update_frequency: "unknown",
    known_gaps: [
      "Search page and linked documents only; no documented bulk API. Do not assume an undocumented bulk API (commission constraint). Document manifest and hash-preserving fetch are SEQRA-04 scope.",
    ],
    ...runtimeFields(),
  },
  {
    source_id: "nys_dec_enb_current",
    source_name: "NYS DEC Environmental Notice Bulletin (current)",
    publisher: "New York State Department of Environmental Conservation",
    jurisdiction_level: "NYS",
    environmental_regime: "SEQRA",
    tier: 2,
    access_type: "discovery_probe",
    base_url: "https://dec.ny.gov/environmental-protection/environmental-notice-bulletin",
    dataset_identifier: "unknown",
    coverage_start: "current_week",
    coverage_end: "current",
    update_frequency: "weekly",
    known_gaps: [
      "Filterable HTML only; rolling current-week window. A separate adapter is required for the historical archive (commission constraint) -- see nys_dec_enb_historical_archive, registered independently.",
    ],
    ...runtimeFields(),
  },
  {
    source_id: "nys_dec_enb_historical_archive",
    source_name: "NYS DEC Environmental Notice Bulletin (historical archive)",
    publisher: "New York State Department of Environmental Conservation",
    jurisdiction_level: "NYS",
    environmental_regime: "SEQRA",
    tier: 2,
    access_type: "discovery_only",
    base_url: "https://dec.ny.gov/environmental-protection/environmental-notice-bulletin/enb-archives",
    dataset_identifier: "unknown",
    coverage_start: "unknown",
    coverage_end: "unknown",
    update_frequency: "static_archive",
    known_gaps: [
      "Deliberately kept as a separate registry entry from the current bulletin per the commission's historical-archive constraint. Not probed in SEQRA-01; archive pagination and per-notice structure are undiscovered.",
    ],
    ...runtimeFields(),
  },
  {
    source_id: "nyc_oec_ceqr_resources",
    source_name: "NYC OEC CEQR resources (technical manual, forms, glossary, calendar)",
    publisher: "NYC Mayor's Office of Environmental Coordination",
    jurisdiction_level: "NYC",
    environmental_regime: "CEQR",
    tier: 2,
    access_type: "discovery_probe",
    base_url: "https://www.nyc.gov/site/oec/technical-guidance/technical-guidance.page",
    dataset_identifier: "unknown",
    coverage_start: "unknown",
    coverage_end: "current",
    update_frequency: "unknown",
    known_gaps: [
      "Reference/manual content, not a review population source. Used later for manual-vintage crosswalks (SEQRA-05), not for counts.",
    ],
    ...runtimeFields(),
  },
  {
    source_id: "lead_agency_project_pages",
    source_name: "Lead-agency project pages (state-led and legacy records)",
    publisher: "various New York State and City lead agencies",
    jurisdiction_level: "NYS",
    environmental_regime: "SEQRA",
    tier: 2,
    access_type: "discovery_only",
    base_url: "unknown",
    dataset_identifier: "unknown",
    coverage_start: "unknown",
    coverage_end: "unknown",
    update_frequency: "unknown",
    known_gaps: [
      "No single documented interface named in the commission; each lead agency publishes independently. Per-agency discovery is out of scope for SEQRA-01.",
    ],
    ...runtimeFields(),
  },
  {
    source_id: "cb_bp_cpc_bsa_lpc_hpd_edc_records",
    source_name: "Community Board, Borough President, CPC, BSA, LPC, HPD and EDC records",
    publisher: "various NYC agencies and local boards",
    jurisdiction_level: "NYC",
    environmental_regime: "CEQR",
    tier: 2,
    access_type: "discovery_only",
    base_url: "unknown",
    dataset_identifier: "unknown",
    coverage_start: "unknown",
    coverage_end: "unknown",
    update_frequency: "unknown",
    known_gaps: [
      "Heterogeneous set of resolutions, recommendations, appeals, and conditions across multiple bodies; no single documented interface named in the commission. Per-body discovery is out of scope for SEQRA-01.",
    ],
    ...runtimeFields(),
  },

  // ---- Tier 3: spatial and implementation context (registered, not probed) ----
  {
    source_id: "spatial_implementation_context",
    source_name: "Historical spatial and implementation sources (PLUTO/MapPLUTO, DOB, BIS, ACRIS, zoning, historic, parks, schools, remediation, disadvantaged-community, flood layers)",
    publisher: "various NYC/NYS agencies",
    jurisdiction_level: "NYC",
    environmental_regime: "CEQR",
    tier: 3,
    access_type: "discovery_only",
    base_url: "unknown",
    dataset_identifier: "unknown",
    coverage_start: "unknown",
    coverage_end: "unknown",
    update_frequency: "unknown",
    known_gaps: [
      "All time-varying spatial sources require a historical vintage; current PLUTO must not silently describe a historical project (commission constraint). Versioned joins are SEQRA-06 scope, not SEQRA-01. Not probed in this card.",
    ],
    ...runtimeFields(),
  },

  // ---- Tier 4: court sources (registered, not probed -- see A78-03) ----
  {
    source_id: "ny_official_reports",
    source_name: "New York Official Reports",
    publisher: "New York State Unified Court System",
    jurisdiction_level: "NYS",
    environmental_regime: "SEQRA",
    tier: 4,
    access_type: "discovery_only",
    base_url: "https://www.nycourts.gov/reporter",
    dataset_identifier: "unknown",
    coverage_start: "unknown",
    coverage_end: "unknown",
    update_frequency: "unknown",
    known_gaps: [
      "Official Reports are incomplete as a filing denominator (commission constraint); published opinions omit many filings, settlements, and discontinuances. Not probed in SEQRA-01; bounded-search coverage receipts are A78-03 scope.",
    ],
    ...runtimeFields(),
  },
  {
    source_id: "ny_slip_opinion_service",
    source_name: "New York Slip Opinion Service",
    publisher: "New York State Unified Court System",
    jurisdiction_level: "NYS",
    environmental_regime: "SEQRA",
    tier: 4,
    access_type: "discovery_only",
    base_url: "https://www.nycourts.gov/reporter/slipidx/slipidx.shtml",
    dataset_identifier: "unknown",
    coverage_start: "unknown",
    coverage_end: "unknown",
    update_frequency: "unknown",
    known_gaps: ["Not probed in SEQRA-01; bounded-search coverage receipts are A78-03 scope."],
    ...runtimeFields(),
  },
  {
    source_id: "nyscef",
    source_name: "NYSCEF",
    publisher: "New York State Unified Court System",
    jurisdiction_level: "NYS",
    environmental_regime: "SEQRA",
    tier: 4,
    access_type: "discovery_only",
    base_url: "https://iapps.courts.state.ny.us/nyscef",
    dataset_identifier: "unknown",
    coverage_start: "unknown",
    coverage_end: "unknown",
    update_frequency: "unknown",
    known_gaps: [
      "Requires bounded-search coverage receipts, not a population count (commission constraint). Not probed in SEQRA-01; A78-03 scope.",
    ],
    ...runtimeFields(),
  },
  {
    source_id: "webcivil_supreme",
    source_name: "WebCivil Supreme",
    publisher: "New York State Unified Court System",
    jurisdiction_level: "NYS",
    environmental_regime: "SEQRA",
    tier: 4,
    access_type: "discovery_only",
    base_url: "https://iapps.courts.state.ny.us/webcivil",
    dataset_identifier: "unknown",
    coverage_start: "unknown",
    coverage_end: "unknown",
    update_frequency: "unknown",
    known_gaps: [
      "Requires bounded-search coverage receipts, not a population count (commission constraint). Not probed in SEQRA-01; A78-03 scope.",
    ],
    ...runtimeFields(),
  },
  {
    source_id: "verified_agency_or_party_announcements",
    source_name: "Verified agency or party announcements",
    publisher: "various New York agencies and litigation parties",
    jurisdiction_level: "NYS",
    environmental_regime: "SEQRA",
    tier: 4,
    access_type: "discovery_only",
    base_url: "unknown",
    dataset_identifier: "unknown",
    coverage_start: "unknown",
    coverage_end: "unknown",
    update_frequency: "unknown",
    known_gaps: ["No single documented interface; verified case-by-case. Not probed in SEQRA-01."],
    ...runtimeFields(),
  },
]);

export function getSeqraSourceRegistryEntry(sourceId) {
  return SEQRA_SOURCE_REGISTRY.find((entry) => entry.source_id === sourceId) ?? null;
}

export function seqraSourceRegistryByTier() {
  const byTier = { 1: [], 2: [], 3: [], 4: [] };
  for (const entry of SEQRA_SOURCE_REGISTRY) byTier[entry.tier].push(entry.source_id);
  return byTier;
}
